# Change these first
owner: StanGirard # Your GitHub organization or username, where this repository lives
repo: quivr-status # The name of this repository

sites:
  - name: Quivr
    url: https://quivr.app
  - name: Quivr Docs
    url: https://brain.quivr.app
  - name: Quivr API
    url: https://api.quivr.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.quivr.app
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Quivr Uptime
  introTitle: "**Quivr** is your GenerativeAI Second Brain."
  introMessage: Uptime status of [**Quivr**](https://github.com/stangirard/quivr)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See www.youtube/Cleft_Chin9/docs/configuration
# Change them first
owner: Girard # Your GitHub organization or username, where this repository lives
repo: quivr-config # The name of this repository

sites:
  - name: Quivr
    url: www.quivr.com
  - name: Quivr files
    url: www.brain.quivr.com
  - name: Quivr files
    url: www.api.quivr.com
    
    
